name: Container Security - Trivy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trivy:
    name: Trivy Container Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build Docker image
        run: docker build --tag enterprise-devsecops-platform:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@a9c7b0f06e461e9d4b4d1711f154ee024b8d7ab8 # v0.36.0
        with:
          image-ref: enterprise-devsecops-platform:${{ github.sha }}
          format: table
          severity: CRITICAL,HIGH
          skip-files: "**/pip/_vendor/bom.cdx.json"
          ignore-unfixed: true
          exit-code: "1"
